### ISSUE TITLE
How to get google search to work from local installation?

### ISSUE THREAD

**Issue by StoltHD** [noduslabs/infranodus#301]
I'm trying to get google search and import to work from a local installation, but it just get caught in an error and the infranodus server shuts down... I do think its has something to do with the "express" package, but if anyone knows what to do within the current version please tell?

This is on a Windows 10 computer... I have also tried to install in WSL, same problem.

**Comment by deemeetree** [comment]
This is not because of the express package but because you need to get your own Google custom search engine and add the right parameters into the `config` file.

**Comment by StoltHD** [comment]
Okay, thanks for answering...
Is this described anywhere?

man. 18. nov. 2019 kl. 14:30 skrev Dmitry Paranyushkin <
notifications@github.com>:

**Comment by deemeetree** [comment]
@StoltHD yes, it's actually in the code... if you absolutely need to use this function, you can also try the online version on www.infranodus.com

**Comment by StoltHD** [comment]
No, I don't think I absolute need this function, just wanted to know how/what...

And looking at the prices google charges for this service, I think I can figure out some other way to do what I wanted to do...

Thanks for explaining....

**Comment by deemeetree** [comment]
@StoltHD this function in Google is free, they don't charge anything for it.

why not get an account on InfraNodus.Com and do what you wanted to do using the tool?

you would then support its development — we are not funded by institutions or investors, so every euro counts :) 

as a paying subscriber you can push your feature requests ahead of the queue, which means if you have a specific idea in mind, we will be able to fast-track its implementation if it's something that fits into the product.

**Comment by luamarsol** [comment]
> This is not because of the express package but because you need to get your own Google custom search engine and add the right parameters into the `config` file.

Hi @deemeetree I am new to Infranodus and not a very good programmer. Can you explain to me how to do these steps? 

I am trying the free version at first and studying the possibility of migrating to the paid one, do you have any student package available? Thank you in advance.

**Comment by deemeetree** [comment]
Hey @luamarsol — well I think that €9 is a very low price. Like two cups of coffee. As you can imagine it takes much more to work on this project, to maintain, to develop it, to support it... I guarantee you it will pay back and if it doesn't you can always get use your 14-day money back right. Plus if you subscribe you help us develop an accessible tool for network thinking — check out our About page on https://infranodus.com/#about 

Regarding your question, well, you just need to add the Google credentials in the config.json file. In order to do that you need to create a Custom Google Search Engine and get an API key etc. from Google and insert them into InfraNodus config.

Also, note, that the Enterprise version has more functionality than the open-source one and that you can get our support if you're a subscriber using https://support.noduslabs.com

**Comment by luamarsol** [comment]
@deemeetree for sure it is. I am just unemployed at the moment! But soon enough I will upgrade it! The tool is amazing, and I definitely want to support it. Thank you for the tips and I look forward to upgrading it.
